In [7]:
import pandas as pd

In [8]:
data=pd.read_csv("insurance.csv")
df=pd.DataFrame(data)

In [9]:
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [10]:
data=pd.read_csv(r"C:\Users\nirma\bhuvana\insurance.csv")
df=pd.DataFrame(data)

In [11]:
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [14]:
data=pd.read_csv(r"C:\Users\nirma\ads.csv")
df=pd.DataFrame(data)

In [15]:
df.head(5)

                  Time     Ads
0  2017-09-13T00:00:00   80115
1  2017-09-13T01:00:00   79885
2  2017-09-13T02:00:00   89325
3  2017-09-13T03:00:00  101930
4  2017-09-13T04:00:00  121630

In [18]:
df.columns

Index(['Time', 'Ads'], dtype='object')

In [19]:
df.head(3)

                  Time    Ads
0  2017-09-13T00:00:00  80115
1  2017-09-13T01:00:00  79885
2  2017-09-13T02:00:00  89325

In [20]:
df.tail(3)

                    Time     Ads
213  2017-09-21T21:00:00  103080
214  2017-09-21T22:00:00   95155
215  2017-09-21T23:00:00   80285

In [21]:
df.shape

(216, 2)

In [23]:
data=pd.read_csv("insurance.csv")
df=pd.DataFrame(data)

In [24]:
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [25]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [26]:
df.tail(3)

      age     sex    bmi  children smoker     region     charges
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [27]:
df.shape

(1338, 7)