In [13]:
import pandas as pd

In [14]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [15]:
s.dtype

dtype('int64')

In [16]:
s.values

array([10, 20, 30, 40, 50])

In [17]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [18]:
print(s.name)

None

In [19]:
s.name="numbers"
print(s.name)

numbers

In [20]:
print(s.name)

numbers

In [21]:
#indexing
s[0]

np.int64(10)

In [22]:
s[0:2]

0    10
1    20
Name: numbers, dtype: int64

In [23]:
s[2:4]

2    30
3    40
Name: numbers, dtype: int64

In [24]:
#iloc -location based indexing
s.iloc[3]

np.int64(40)

In [25]:
s[3]

np.int64(40)

In [26]:
s.iloc[[1,2,3]]

1    20
2    30
3    40
Name: numbers, dtype: int64

In [27]:
id=[100,200,300,400,500]
s.index=id
s

100    10
200    20
300    30
400    40
500    50
Name: numbers, dtype: int64

In [28]:
s[200]

np.int64(20)

In [29]:
s.iloc[3]

np.int64(40)

In [30]:
s.loc[100:300]

100    10
200    20
300    30
Name: numbers, dtype: int64

In [31]:
class_data={"name":1,"marks":100,"Age":20,"Subject":4}

In [32]:
s2=pd.Series(class_data,name="College")
s2

name         1
marks      100
Age         20
Subject      4
Name: College, dtype: int64

In [33]:
s2.iloc[3]

np.int64(4)

In [34]:
s2.loc["Age"]

np.int64(20)

In [35]:
#Conditional selection
s2[s2>20]

marks    100
Name: College, dtype: int64

In [36]:
#Logical Operators
s2[(s2>4) &(s2<100)]

Age    20
Name: College, dtype: int64

In [37]:
s2[~(s2>20)]

name        1
Age        20
Subject     4
Name: College, dtype: int64

In [38]:
#modify the series
s2["Age"]=34
3
s2

name         1
marks      100
Age         34
Subject      4
Name: College, dtype: int64

In [39]:
#dataframes

In [40]:
import numpy as np
import pandas as pd
ser=pd.Series(['a',np.nan,1,np.nan,2])
ser.notnull().sum()

np.int64(3)

In [41]:
data={
      "Name":["krish","kumar","reddy","minsuu","mahitha","vishwa"],
      "Age":[25,34,32,42,33,43],
      "Department":["HR","IT","Finance","IT","HR","HR"],
      "Salary":[50000,60000,70000,62000,np.nan,50000]
}
data

{'Name': ['krish', 'kumar', 'reddy', 'minsuu', 'mahitha', 'vishwa'],
 'Age': [25, 34, 32, 42, 33, 43],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [42]:
data

{'Name': ['krish', 'kumar', 'reddy', 'minsuu', 'mahitha', 'vishwa'],
 'Age': [25, 34, 32, 42, 33, 43],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [43]:
df=pd.DataFrame(data)
df

      Name  Age Department   Salary
0    krish   25         HR  50000.0
1    kumar   34         IT  60000.0
2    reddy   32    Finance  70000.0
3   minsuu   42         IT  62000.0
4  mahitha   33         HR      NaN
5   vishwa   43         HR  50000.0

In [44]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='object')

In [45]:
df.head(3)

    Name  Age Department   Salary
0  krish   25         HR  50000.0
1  kumar   34         IT  60000.0
2  reddy   32    Finance  70000.0

In [46]:
df.head(5)

      Name  Age Department   Salary
0    krish   25         HR  50000.0
1    kumar   34         IT  60000.0
2    reddy   32    Finance  70000.0
3   minsuu   42         IT  62000.0
4  mahitha   33         HR      NaN

In [47]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='object')

In [48]:
df.head(3)

    Name  Age Department   Salary
0  krish   25         HR  50000.0
1  kumar   34         IT  60000.0
2  reddy   32    Finance  70000.0

In [49]:
df.tail(3)

      Name  Age Department   Salary
3   minsuu   42         IT  62000.0
4  mahitha   33         HR      NaN
5   vishwa   43         HR  50000.0

In [50]:
#loc and iloc
df.iloc[1:3]

    Name  Age Department   Salary
1  kumar   34         IT  60000.0
2  reddy   32    Finance  70000.0

In [51]:
df.loc[1:3]

     Name  Age Department   Salary
1   kumar   34         IT  60000.0
2   reddy   32    Finance  70000.0
3  minsuu   42         IT  62000.0

In [52]:
df.loc[1:3,["Age","Department"]]

   Age Department
1   34         IT
2   32    Finance
3   42         IT

In [53]:
df.loc[1:5,"Department"]

1         IT
2    Finance
3         IT
4         HR
5         HR
Name: Department, dtype: object

In [54]:
df.iloc[1:5,2:]

  Department   Salary
1         IT  60000.0
2    Finance  70000.0
3         IT  62000.0
4         HR      NaN

In [55]:
df.iloc[1:5,:2]

      Name  Age
1    kumar   34
2    reddy   32
3   minsuu   42
4  mahitha   33

In [56]:
df["Age"]

0    25
1    34
2    32
3    42
4    33
5    43
Name: Age, dtype: int64

In [57]:
df[["Age","Department"]]

   Age Department
0   25         HR
1   34         IT
2   32    Finance
3   42         IT
4   33         HR
5   43         HR

In [58]:
df.drop("Age",axis=1)

      Name Department   Salary
0    krish         HR  50000.0
1    kumar         IT  60000.0
2    reddy    Finance  70000.0
3   minsuu         IT  62000.0
4  mahitha         HR      NaN
5   vishwa         HR  50000.0

In [59]:
df

      Name  Age Department   Salary
0    krish   25         HR  50000.0
1    kumar   34         IT  60000.0
2    reddy   32    Finance  70000.0
3   minsuu   42         IT  62000.0
4  mahitha   33         HR      NaN
5   vishwa   43         HR  50000.0

In [60]:
df.drop("Age",axis=1,inplace=True)

In [61]:
df

      Name Department   Salary
0    krish         HR  50000.0
1    kumar         IT  60000.0
2    reddy    Finance  70000.0
3   minsuu         IT  62000.0
4  mahitha         HR      NaN
5   vishwa         HR  50000.0

In [62]:
df["Age"]=[32,35,35,20,np.nan,45]
df

      Name Department   Salary   Age
0    krish         HR  50000.0  32.0
1    kumar         IT  60000.0  35.0
2    reddy    Finance  70000.0  35.0
3   minsuu         IT  62000.0  20.0
4  mahitha         HR      NaN   NaN
5   vishwa         HR  50000.0  45.0

In [63]:
df.shape

(6, 4)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Salary      5 non-null      float64
 3   Age         5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [65]:
df.describe()

             Salary        Age
count      5.000000   5.000000
mean   58400.000000  33.400000
std     8532.291603   8.961027
min    50000.000000  20.000000
25%    50000.000000  32.000000
50%    60000.000000  35.000000
75%    62000.000000  35.000000
max    70000.000000  45.000000

In [66]:
df["Salary"]

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4        NaN
5    50000.0
Name: Salary, dtype: float64

In [67]:
#Broadcasting
df["Salary"]=df["Salary"]+5000

In [68]:
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [69]:
#rename
df.rename(columns={"Department":"Dept"},inplace=True)

In [70]:
df

      Name     Dept   Salary   Age
0    krish       HR  55000.0  32.0
1    kumar       IT  65000.0  35.0
2    reddy  Finance  75000.0  35.0
3   minsuu       IT  67000.0  20.0
4  mahitha       HR      NaN   NaN
5   vishwa       HR  55000.0  45.0

In [71]:
#Unique Values
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [72]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [73]:
#count
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [74]:
df["Promoted_Salary"]=df["Salary"]*10

In [75]:
df

      Name     Dept   Salary   Age  Promoted_Salary
0    krish       HR  55000.0  32.0         550000.0
1    kumar       IT  65000.0  35.0         650000.0
2    reddy  Finance  75000.0  35.0         750000.0
3   minsuu       IT  67000.0  20.0         670000.0
4  mahitha       HR      NaN   NaN              NaN
5   vishwa       HR  55000.0  45.0         550000.0

In [76]:
#Data Cleaning
df.isnull().sum()

Name               0
Dept               0
Salary             1
Age                1
Promoted_Salary    1
dtype: int64

In [77]:
df.dropna()

     Name     Dept   Salary   Age  Promoted_Salary
0   krish       HR  55000.0  32.0         550000.0
1   kumar       IT  65000.0  35.0         650000.0
2   reddy  Finance  75000.0  35.0         750000.0
3  minsuu       IT  67000.0  20.0         670000.0
5  vishwa       HR  55000.0  45.0         550000.0

In [78]:
df

      Name     Dept   Salary   Age  Promoted_Salary
0    krish       HR  55000.0  32.0         550000.0
1    kumar       IT  65000.0  35.0         650000.0
2    reddy  Finance  75000.0  35.0         750000.0
3   minsuu       IT  67000.0  20.0         670000.0
4  mahitha       HR      NaN   NaN              NaN
5   vishwa       HR  55000.0  45.0         550000.0

In [79]:
#if any of the row value is null del total row
df.dropna(how="any")

     Name     Dept   Salary   Age  Promoted_Salary
0   krish       HR  55000.0  32.0         550000.0
1   kumar       IT  65000.0  35.0         650000.0
2   reddy  Finance  75000.0  35.0         750000.0
3  minsuu       IT  67000.0  20.0         670000.0
5  vishwa       HR  55000.0  45.0         550000.0

In [80]:
#if all the values in the row them del whole row
df.dropna(how="all")

      Name     Dept   Salary   Age  Promoted_Salary
0    krish       HR  55000.0  32.0         550000.0
1    kumar       IT  65000.0  35.0         650000.0
2    reddy  Finance  75000.0  35.0         750000.0
3   minsuu       IT  67000.0  20.0         670000.0
4  mahitha       HR      NaN   NaN              NaN
5   vishwa       HR  55000.0  45.0         550000.0

In [81]:
#replace null values
df["Age"].fillna(df["Age"].mean())

0    32.0
1    35.0
2    35.0
3    20.0
4    33.4
5    45.0
Name: Age, dtype: float64

In [82]:
#null value with median
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [83]:
df["Age"].fillna(method="ffill")

C:\Users\nirma\AppData\Local\Temp\ipykernel_13808\310954073.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")

0    32.0
1    35.0
2    35.0
3    20.0
4    20.0
5    45.0
Name: Age, dtype: float64

In [84]:
df["Age"].fillna(method="bfill")

C:\Users\nirma\AppData\Local\Temp\ipykernel_13808\3345892411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="bfill")

0    32.0
1    35.0
2    35.0
3    20.0
4    45.0
5    45.0
Name: Age, dtype: float64

In [85]:
#replacing a value
df["Name"]=df["Name"].replace("reddy","juliee")

In [86]:
df

      Name     Dept   Salary   Age  Promoted_Salary
0    krish       HR  55000.0  32.0         550000.0
1    kumar       IT  65000.0  35.0         650000.0
2   juliee  Finance  75000.0  35.0         750000.0
3   minsuu       IT  67000.0  20.0         670000.0
4  mahitha       HR      NaN   NaN              NaN
5   vishwa       HR  55000.0  45.0         550000.0

In [87]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [88]:
df.loc[len(df)]=["Bob","HR",55000.0,45,550000.0]
df

      Name     Dept   Salary   Age  Promoted_Salary
0    krish       HR  55000.0  32.0         550000.0
1    kumar       IT  65000.0  35.0         650000.0
2   juliee  Finance  75000.0  35.0         750000.0
3   minsuu       IT  67000.0  20.0         670000.0
4  mahitha       HR      NaN   NaN              NaN
5   vishwa       HR  55000.0  45.0         550000.0
6      Bob       HR  55000.0  45.0         550000.0

In [89]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [90]:
df_dup=df[df.duplicated(keep="first")]
df_dup

Empty DataFrame
Columns: [Name, Dept, Salary, Age, Promoted_Salary]
Index: []

In [91]:
import pandas as pd

In [92]:
df_dup=df[df.duplicated(keep="last")]
df_dup

Empty DataFrame
Columns: [Name, Dept, Salary, Age, Promoted_Salary]
Index: []

In [93]:
df=df.drop_duplicates
df

<bound method DataFrame.drop_duplicates of       Name     Dept   Salary   Age  Promoted_Salary
0    krish       HR  55000.0  32.0         550000.0
1    kumar       IT  65000.0  35.0         650000.0
2   juliee  Finance  75000.0  35.0         750000.0
3   minsuu       IT  67000.0  20.0         670000.0
4  mahitha       HR      NaN   NaN              NaN
5   vishwa       HR  55000.0  45.0         550000.0
6      Bob       HR  55000.0  45.0         550000.0>

In [5]:
'''name="alice_fernandes"
df[["first_name","last_name"]]=df["name"].str.split("_")'''

'name="alice_fernandes"\ndf[["first_name","last_name"]]=df["name"].str.split("_")'

In [6]:
#apply and lambda
def multiplying_age(x):
                       return x*2
                       df["Age"]=df["Age"].apply(multiplying_age)

In [8]:
df

NameError: name 'df' is not defined

In [1]:
#joins and merges
department_info={
"Dept":["HR","IT","Finance"],
"Location":["New York","San Francisco","Chicago"],
"Manager":["Laura","Steve","Nina"]
}
df2=pd.DataFrame(department_info)

NameError: name 'pd' is not defined

In [2]:
#concat
pd.concat([df,df2])

NameError: name 'pd' is not defined

In [3]:
pd.concat([df,df2],axis=1)

NameError: name 'pd' is not defined

In [4]:
pd.merge(df,df2,on="Dept")

NameError: name 'pd' is not defined